nav:
  - Home: 
    - index.md
    - 关于我: home/about.md
    - 项目介绍: 
      - 毕业论文: project/GraduationThesis.md
      - 嵌入式: project/embedded.md
  - mkdocs: 
    - 代码示例: mkdocs/code-examples.md
    - 标签示例: mkdocs/content-tabs.md
    - 图标示例: mkdocs/diagram-examples.md
    - 警告示例: mkdocs/admonitions.md
  - 核心专业课:
    - 程序设计基础:
      - SpecializedCourse/c/第1章 c语言概述.md
      - SpecializedCourse/c/第2章 C语言基本概念.md
      - SpecializedCourse/c/第3章 格式化输入输出.md
      - SpecializedCourse/c/第4章 表达式.md
      - SpecializedCourse/c/第5章 选择语句.md
      - SpecializedCourse/c/第6章 循环.md
      - SpecializedCourse/c/第7章 基本类型.md
      - SpecializedCourse/c/第8章 数组.md
      - SpecializedCourse/c/第9章 函数.md
      - SpecializedCourse/c/第10章 程序结构.md
      - SpecializedCourse/c/第11章 指针.md
      - SpecializedCourse/c/第12章 指针和数组.md
      - SpecializedCourse/c/第13章 字符串.md
      - SpecializedCourse/c/第14章 预处理器.md
      - SpecializedCourse/c/第16章 结构、联合和枚举.md
      - SpecializedCourse/c/第17章 指针的高级应用.md
    - 数据结构: 
      - 绪论: SpecializedCourse/datastructure/xulun.md
      - SpecializedCourse/datastructure/2.4 线性表的顺序表示和实现.md
      - SpecializedCourse/datastructure/2.5 线性表的链式表示和实现.md
      - SpecializedCourse/datastructure/3.4 栈与递归.md
      - SpecializedCourse/datastructure/6.1 图的定义和基本术语.md
      - SpecializedCourse/datastructure/6.5 图的遍历.md
      - SpecializedCourse/datastructure/6.6 最小生成树.md
      - SpecializedCourse/datastructure/7.1 查找的基本概念.md
      - SpecializedCourse/datastructure/7.3 树表的查找.md
      - SpecializedCourse/datastructure/7.3.2 平衡二叉树.md
      - SpecializedCourse/datastructure/7.4.1 散列表的基本概念.md
      - SpecializedCourse/datastructure/8.1 基本概念和排序方法概述.md
      - SpecializedCourse/datastructure/8.2 插入排序.md
      - SpecializedCourse/datastructure/8.3 交换排序.md
      - SpecializedCourse/datastructure/8.4选择排序.md
      - SpecializedCourse/datastructure/8.5归并排序.md
      - SpecializedCourse/datastructure/8.7 外部排序.md
      - SpecializedCourse/datastructure/算法与算法分析.md
    - 计算机组成: 
      - SpecializedCourse/computerzuchen/4.1 存储器概述.md
      - SpecializedCourse/computerzuchen/4.2 半导体存储器.md
      - SpecializedCourse/computerzuchen/4.3 主存的组织及与CPU的连接.md
      - SpecializedCourse/computerzuchen/4.4 并行主存系统.md
      - SpecializedCourse/computerzuchen/4.5 高速缓冲存储器.md
      - SpecializedCourse/computerzuchen/4.6虚拟存储器.md
      - SpecializedCourse/computerzuchen/5.1 指令系统概述.md
      - SpecializedCourse/computerzuchen/5.2 指令格式.md
      - SpecializedCourse/computerzuchen/5.3 The Basics of Caches.md
      - SpecializedCourse/computerzuchen/5.3 寻址方式.md
      - SpecializedCourse/computerzuchen/5.4 指令类型.md
      - SpecializedCourse/computerzuchen/5.5 指令格式设计.md
      - SpecializedCourse/computerzuchen/5.6 CISC和RISC.md
      - SpecializedCourse/computerzuchen/5.7 指令系统举例.md
      - SpecializedCourse/computerzuchen/6.1 中央处理器概述.md
      - SpecializedCourse/computerzuchen/6.2 指令周期.md
      - SpecializedCourse/computerzuchen/6.3 数据通路及指令操作流程.md
      - SpecializedCourse/computerzuchen/6.4 时序与控制.md
      - SpecializedCourse/computerzuchen/6.5 硬布线控制器.md
      - SpecializedCourse/computerzuchen/6.6 微程序控制器.md
      - SpecializedCourse/computerzuchen/6.7 异常与中断处理.md
      - SpecializedCourse/computerzuchen/8.1 总线概述.md
      - SpecializedCourse/computerzuchen/8.2 总线传输机制.md
      - SpecializedCourse/computerzuchen/8.3 总线结构.md
      - SpecializedCourse/computerzuchen/8.4 常用总线.md
      - SpecializedCourse/computerzuchen/9.1 输入输出设备与特性.md
      - SpecializedCourse/computerzuchen/9.2 IO接口.md
      - SpecializedCourse/computerzuchen/9.3 数据传输控制方式.md
      - SpecializedCourse/computerzuchen/9.4 程序控制方式.md
      - SpecializedCourse/computerzuchen/9.5 程序中断控制方式.md
      - SpecializedCourse/computerzuchen/9.6 DMA方式.md
      - SpecializedCourse/computerzuchen/9.7 通道方式(不考).md
      - SpecializedCourse/computerzuchen/9.8 常见IO设备.md
    - 操作系统: 
      - SpecializedCourse/os/3.1 Process Concept.md
      - SpecializedCourse/os/3.2 Process Scheduling.md
      - SpecializedCourse/os/3.3 Operations on Processes.md
      - SpecializedCourse/os/3.4 Interprocess Communication.md
      - SpecializedCourse/os/3.5 IPC In Shared-Memory Systems.md
      - SpecializedCourse/os/3.6 IPC in Message-Passing Systems.md
      - SpecializedCourse/os/3.7 3.8.md
      - SpecializedCourse/os/4.1 Threads & Concurrency Overview.md
      - SpecializedCourse/os/4.2 Multicore Programming.md
      - SpecializedCourse/os/4.3 Multithreading Models.md
      - SpecializedCourse/os/5.1 CPU Scheduling Basic Concepts.md
      - SpecializedCourse/os/5.2 Scheduling Criteria.md
      - SpecializedCourse/os/5.3 Scheduling Algorithms.md
      - SpecializedCourse/os/7 Synchronization Examples.md
      - SpecializedCourse/os/9 Main Memory.md
      - SpecializedCourse/os/11 Mass-Storage Structure.md
      - SpecializedCourse/os/Chapter 6 Synchronization Tools.md
      - SpecializedCourse/os/Chapter 8 Deadlocks.md

    - 计算机网络: 
      - SpecializedCourse/internet/2.1 Principles of Network Applications.md
      - SpecializedCourse/internet/2.2 The Web and HTTP.md
      - SpecializedCourse/internet/2.3 Electronic Mail in the Internet.md
      - SpecializedCourse/internet/2.4 DNS---The Internet's Directory Service.md
      - SpecializedCourse/internet/2.5 Peer-to-Peer File Distribution.md
      - SpecializedCourse/internet/3.1 Introduction and Transport-Layer Services.md
      - SpecializedCourse/internet/3.2 Multiplexing and Demultiplexing.md
      - SpecializedCourse/internet/3.3 Connectionless Transport UDP.md
      - SpecializedCourse/internet/3.4 Principles of Reliable Data Transfer.md
      - SpecializedCourse/internet/3.5 Connection-Oriented Transport TCP.md
      - SpecializedCourse/internet/3.6 Principles of Congestion Control.md
      - SpecializedCourse/internet/3.7 TCP Congestion Control.md
      - SpecializedCourse/internet/4.1 Overview of Network Layer.md
      - SpecializedCourse/internet/4.2 What's Inside a Router.md
      - SpecializedCourse/internet/4.3 The Internet Protocol(IP) IPv4,Addressing,IPv6,and More.md
      - SpecializedCourse/internet/4.4 Generalized Forwarding and SDN.md
      - SpecializedCourse/internet/FTP.md
    - 数据库: SpecializedCourse/database/data1.md
  - 数学:
    - 高等数学: math/gaodengmath/1.md
    - 线性代数: 
      - 陈发来线性代数笔记: math/linearAlgebra/1.md
      - 李永乐强化笔记: math/linearAlgebra/2.md
    - 离散数学: 
      - 集合论与图论: math/Discretemathematics/set.md
      - 数理逻辑: math/Discretemathematics/logic.md
      - 抽象代数: math/Discretemathematics/3.md
    - 概率论与数理统计: math/probability/1.md




site_name: 阿鸣的笔记
site_url: https://chenaming.github.io/
site_description: A blogging site
repo_name: chenaming/阿鸣的笔记
repo_url: https://github.com/chenaming/chenaming.github.io-main
edit_uri: edit/main/docs/


theme:
  name: material

  favicon: logo.ico
  font:
    text: Comic Neue
    code: Red Hat Mono
  custom_dir: overrides

  features:
    - content.action.edit # 编辑按钮
    - content.action.view # 查看源代码按钮
    - content.code.copy # 支持代码块复制
    - navigation.footer # 上一页和下一页
    - navigation.tabs # 一级导航在横着的导航栏
    - content.code.annotate # 可以在代码块中增添点击展示的注释，参见 https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    # - navigation.tracking # 地址栏中的 URL 会随当前位置变化为对应小节的 URL
    - navigation.indexes # 将 index 页面直接附到小节名上
    - navigation.top # 回到顶部按钮
    # - navigation.sections # 二级导航是粗体
    # - navigation.expand # 导航默认展开
    - toc.follow # toc 跟随
    # - toc.integrate # 文档 toc 集成到总目录中 
    - search.suggest
    - search.highlight
    - search.share
  language: 'zh'
  palette: 
    #Dark Mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      accent: deep purple

    #Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: light mode
      primary: blue
      accent: deep orange


markdown_extensions:
  - toc:
      permalink: true # link for each title

  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - meta
  - md_in_html

  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      # smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets: # 允许将其他文件内容插入文件，语法是 --8<-- "filename.ext" 等，参见 https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#snippets-notation
      auto_append:
        - includes/abbreviations.md
      base_path: ["docs"]
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  analytics:
    provider: google
    property: G-JT9BRCXKJJ
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/chenaming
    - icon: fontawesome/regular/envelope
      link: mailto:chena_ming@outlook.com
      name: Email

copyright: Copyright &copy; 2024 Chenaming

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js


plugins:
  - search:
  - blog:
      enabled: true
      blog_dir: .

      archive_date_format: yyyy
      archive_url_date_format: yyyy
      post_url_format: "{slug}"








